import httpx
from typing import List, Dict

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3" # Defaulting to llama3

async def generate_chat_response(user_message: str, top_hotspots: List[Dict]) -> str:
    # 1. Format the current severe hotspots context
    hotspot_context = ""
    for i, h in enumerate(top_hotspots[:3]):
        hotspot_context += f"{i+1}. {h['junction_name']} (Impact: {h['impact_score']}/10)\n"
        
    if not hotspot_context:
        hotspot_context = "No severe hotspots currently active."

    # 2. Construct the strict System Prompt
    system_prompt = (
        "You are Gridlock AI, a tactical dispatcher for Bengaluru traffic police. "
        f"Current severe hotspots:\n{hotspot_context}\n"
        "Keep answers under 3 sentences. Be highly analytical and authoritative."
    )

    prompt = f"{system_prompt}\n\nDispatcher Query: {user_message}\nGridlock AI:"

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False
    }

    # 3. Call Ollama API
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(OLLAMA_URL, json=payload)
            response.raise_for_status()
            data = response.json()
            return data.get("response", "Error: No response generated by Copilot.")
    except httpx.RequestError as e:
        return f"Gridlock AI Error: Unable to connect to local Ollama instance. Is Ollama running on localhost:11434? Details: {str(e)}"
    except Exception as e:
        return f"Gridlock AI Error: {str(e)}"
